### ISSUE TITLE
PR 참여 방식에 대한 논의

### ISSUE THREAD

**Issue by BKJang** [SeonHyungJo/reactjs-interview-questions-korean#1]
개인적인 생각으로는 react 공식 문서 번역 레포와 같이 번역할 부분을 개개인이 할당해가는 방식으로 정리를 하면 어떨까요?
의견 부탁드립니다.

**Comment by SeonHyungJo** [comment]
같이 작업을 한다면 엑셀이나 이슈하나로 정리하는 것도 좋은 방법인거 같습니다

**Comment by BKJang** [comment]
말씀하신대로 이슈 하나로 정리하는건 어떨까요?
도움이 된다면 같이 참여하도록 하겠습니다 :)

#### Reference
- https://github.com/reactjs/ko.reactjs.org/issues/1

**Comment by SeonHyungJo** [comment]
Contributor 링크는 보내드렸으며 추가적으로 issue에 번역관련 내용으로 작성하고 있습니다. 추가적으로 부족한 내용은 comment를 달아주시면 반영하도록 하겠습니다. #2
