### ISSUE TITLE
번역작업을 하고 싶습니다.

### ISSUE THREAD

**Issue by voidmatcha** [SeonHyungJo/reactjs-interview-questions-korean#315]
안녕하세요. 325. [How do you make sure that user remains authenticated on page refresh while using Context API State Management](https://github.com/sudheerj/reactjs-interview-questions#how-do-you-make-sure-that-user-remains-authenticated-on-page-refresh-while-using-context-api-state-management) 번역을 희망합니다.

제 이메일은 [201704147@cs-cnu.org](mailto:201704147@cs-cnu.org) 입니다.

**Comment by SeonHyungJo** [comment]
@dididy 새로운 내용이 추가된 것을 덕분에 알았습니다.
관련 번역희망하신 부분은 이메일에서 승인을 해주시고 작업하시면 됩니다. 

지켜주셔야할 부분이 있는데 Branch, 커밋 메시지, 맞춤법입니다.
관련 내용은 #2  를 확인해주세요

**Comment by voidmatcha** [comment]
네 알겠습니다. 컨벤션에 맞춰서 작업하도록 하겠습니다. 👍
